name: Update Data and Deploy Streamlit App

on:
  schedule:
    - cron: '20 17 * * *' # Daily trigger at 2 AM UTC

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main # or specify your branch name

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # if you have any dependencies

      - name: Update Data and Generate New Files
        run: |
          python get_data.py
          python create_record_tables.py

      - name: Replace Existing Files
        run: |
          mv all_ipl_data.csv all_ipl_data_old.csv # Rename old combined.csv if needed
          mv cricket_database.db cricket_database_old.db     # Rename old cricket.db if needed
          mv cricket_database.db cricket_database.db

      - name: Deploy Streamlit App
        run: streamlit run cricomania.py
